# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Project\QuantStudio\QuantStudio\Tools\QtGUI\IDSetup.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IDSetupDlg(object):
    def setupUi(self, IDSetupDlg):
        IDSetupDlg.setObjectName("IDSetupDlg")
        IDSetupDlg.resize(401, 342)
        IDSetupDlg.setFocusPolicy(QtCore.Qt.ClickFocus)
        IDSetupDlg.setSizeGripEnabled(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(IDSetupDlg)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.FDBGroupBox = QtWidgets.QGroupBox(IDSetupDlg)
        self.FDBGroupBox.setObjectName("FDBGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.FDBGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.FDBGroupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.FDBGroupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.FDBGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.DateTimeEdit = QtWidgets.QDateTimeEdit(self.FDBGroupBox)
        self.DateTimeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.DateTimeEdit.setObjectName("DateTimeEdit")
        self.gridLayout.addWidget(self.DateTimeEdit, 2, 1, 1, 2)
        self.IgnoreDTCheckBox = QtWidgets.QCheckBox(self.FDBGroupBox)
        self.IgnoreDTCheckBox.setChecked(True)
        self.IgnoreDTCheckBox.setObjectName("IgnoreDTCheckBox")
        self.gridLayout.addWidget(self.IgnoreDTCheckBox, 3, 0, 1, 1)
        self.FIDSelectTypeComboBox = QtWidgets.QComboBox(self.FDBGroupBox)
        self.FIDSelectTypeComboBox.setObjectName("FIDSelectTypeComboBox")
        self.FIDSelectTypeComboBox.addItem("")
        self.FIDSelectTypeComboBox.addItem("")
        self.FIDSelectTypeComboBox.addItem("")
        self.FIDSelectTypeComboBox.addItem("")
        self.FIDSelectTypeComboBox.addItem("")
        self.FIDSelectTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.FIDSelectTypeComboBox, 3, 1, 1, 1)
        self.SelectFDBIDButton = QtWidgets.QPushButton(self.FDBGroupBox)
        self.SelectFDBIDButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SelectFDBIDButton.setObjectName("SelectFDBIDButton")
        self.gridLayout.addWidget(self.SelectFDBIDButton, 3, 2, 1, 1)
        self.FTComboBox = QtWidgets.QComboBox(self.FDBGroupBox)
        self.FTComboBox.setObjectName("FTComboBox")
        self.gridLayout.addWidget(self.FTComboBox, 0, 1, 1, 2)
        self.FactorComboBox = QtWidgets.QComboBox(self.FDBGroupBox)
        self.FactorComboBox.setObjectName("FactorComboBox")
        self.gridLayout.addWidget(self.FactorComboBox, 1, 1, 1, 2)
        self.gridLayout_3.addWidget(self.FDBGroupBox, 0, 0, 2, 3)
        self.label_7 = QtWidgets.QLabel(IDSetupDlg)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 3, 1, 1)
        self.IDNumEdit = QtWidgets.QLineEdit(IDSetupDlg)
        self.IDNumEdit.setReadOnly(True)
        self.IDNumEdit.setObjectName("IDNumEdit")
        self.gridLayout_3.addWidget(self.IDNumEdit, 0, 4, 1, 1)
        self.IDListWidget = QtWidgets.QListWidget(IDSetupDlg)
        self.IDListWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.IDListWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.IDListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.IDListWidget.setObjectName("IDListWidget")
        self.gridLayout_3.addWidget(self.IDListWidget, 1, 3, 2, 2)
        self.IDGroupBox = QtWidgets.QGroupBox(IDSetupDlg)
        self.IDGroupBox.setTitle("")
        self.IDGroupBox.setObjectName("IDGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.IDGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CodeLabel_2 = QtWidgets.QLabel(self.IDGroupBox)
        self.CodeLabel_2.setObjectName("CodeLabel_2")
        self.gridLayout_2.addWidget(self.CodeLabel_2, 0, 0, 1, 1)
        self.IDTypeComboBox = QtWidgets.QComboBox(self.IDGroupBox)
        self.IDTypeComboBox.setObjectName("IDTypeComboBox")
        self.gridLayout_2.addWidget(self.IDTypeComboBox, 0, 1, 1, 2)
        self.CodeLabel = QtWidgets.QLabel(self.IDGroupBox)
        self.CodeLabel.setObjectName("CodeLabel")
        self.gridLayout_2.addWidget(self.CodeLabel, 1, 0, 1, 1)
        self.CodeEdit = QtWidgets.QLineEdit(self.IDGroupBox)
        self.CodeEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.CodeEdit.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.CodeEdit.setObjectName("CodeEdit")
        self.gridLayout_2.addWidget(self.CodeEdit, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.IDGroupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.DateEdit = QtWidgets.QDateEdit(self.IDGroupBox)
        self.DateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.DateEdit.setObjectName("DateEdit")
        self.gridLayout_2.addWidget(self.DateEdit, 2, 1, 1, 2)
        self.CurrentCheckBox = QtWidgets.QCheckBox(self.IDGroupBox)
        self.CurrentCheckBox.setChecked(True)
        self.CurrentCheckBox.setObjectName("CurrentCheckBox")
        self.gridLayout_2.addWidget(self.CurrentCheckBox, 3, 0, 1, 1)
        self.SelectIDTypeComboBox = QtWidgets.QComboBox(self.IDGroupBox)
        self.SelectIDTypeComboBox.setObjectName("SelectIDTypeComboBox")
        self.SelectIDTypeComboBox.addItem("")
        self.SelectIDTypeComboBox.addItem("")
        self.SelectIDTypeComboBox.addItem("")
        self.SelectIDTypeComboBox.addItem("")
        self.SelectIDTypeComboBox.addItem("")
        self.SelectIDTypeComboBox.addItem("")
        self.gridLayout_2.addWidget(self.SelectIDTypeComboBox, 3, 1, 1, 1)
        self.SelectIDButton = QtWidgets.QPushButton(self.IDGroupBox)
        self.SelectIDButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SelectIDButton.setObjectName("SelectIDButton")
        self.gridLayout_2.addWidget(self.SelectIDButton, 3, 2, 1, 1)
        self.gridLayout_3.addWidget(self.IDGroupBox, 2, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        self.AcceptButton = QtWidgets.QPushButton(IDSetupDlg)
        self.AcceptButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.AcceptButton.setObjectName("AcceptButton")
        self.gridLayout_3.addWidget(self.AcceptButton, 3, 1, 1, 1)
        self.RejectButton = QtWidgets.QPushButton(IDSetupDlg)
        self.RejectButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.RejectButton.setObjectName("RejectButton")
        self.gridLayout_3.addWidget(self.RejectButton, 3, 2, 1, 1)
        self.IDInputEdit = QtWidgets.QLineEdit(IDSetupDlg)
        self.IDInputEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.IDInputEdit.setObjectName("IDInputEdit")
        self.gridLayout_3.addWidget(self.IDInputEdit, 3, 3, 1, 2)
        self.CodeLabel_2.setBuddy(self.CodeEdit)
        self.CodeLabel.setBuddy(self.CodeEdit)

        self.retranslateUi(IDSetupDlg)
        QtCore.QMetaObject.connectSlotsByName(IDSetupDlg)
        IDSetupDlg.setTabOrder(self.CodeEdit, self.SelectFDBIDButton)

    def retranslateUi(self, IDSetupDlg):
        _translate = QtCore.QCoreApplication.translate
        IDSetupDlg.setWindowTitle(_translate("IDSetupDlg", "ID 设置"))
        self.FDBGroupBox.setTitle(_translate("IDSetupDlg", "来自因子库"))
        self.label_5.setText(_translate("IDSetupDlg", "因子表"))
        self.label_6.setText(_translate("IDSetupDlg", "因子"))
        self.label_4.setText(_translate("IDSetupDlg", "<html><head/><body><p align=\"center\">时点</p></body></html>"))
        self.DateTimeEdit.setDisplayFormat(_translate("IDSetupDlg", "yyyy-MM-dd HH:mm:ss"))
        self.IgnoreDTCheckBox.setText(_translate("IDSetupDlg", "忽略时点"))
        self.FIDSelectTypeComboBox.setItemText(0, _translate("IDSetupDlg", "覆盖"))
        self.FIDSelectTypeComboBox.setItemText(1, _translate("IDSetupDlg", "并集"))
        self.FIDSelectTypeComboBox.setItemText(2, _translate("IDSetupDlg", "交集"))
        self.FIDSelectTypeComboBox.setItemText(3, _translate("IDSetupDlg", "左差右"))
        self.FIDSelectTypeComboBox.setItemText(4, _translate("IDSetupDlg", "右差左"))
        self.FIDSelectTypeComboBox.setItemText(5, _translate("IDSetupDlg", "对称差"))
        self.SelectFDBIDButton.setText(_translate("IDSetupDlg", ">>"))
        self.label_7.setText(_translate("IDSetupDlg", "ID 数"))
        self.IDNumEdit.setText(_translate("IDSetupDlg", "0"))
        self.CodeLabel_2.setText(_translate("IDSetupDlg", "<html><head/><body><p align=\"center\">ID 类型</p></body></html>"))
        self.CodeLabel.setText(_translate("IDSetupDlg", "<html><head/><body><p align=\"center\">指数代码</p></body></html>"))
        self.label.setText(_translate("IDSetupDlg", "<html><head/><body><p align=\"center\">截止日期</p></body></html>"))
        self.DateEdit.setDisplayFormat(_translate("IDSetupDlg", "yyyy-MM-dd"))
        self.CurrentCheckBox.setText(_translate("IDSetupDlg", "历史成分"))
        self.SelectIDTypeComboBox.setItemText(0, _translate("IDSetupDlg", "覆盖"))
        self.SelectIDTypeComboBox.setItemText(1, _translate("IDSetupDlg", "并集"))
        self.SelectIDTypeComboBox.setItemText(2, _translate("IDSetupDlg", "交集"))
        self.SelectIDTypeComboBox.setItemText(3, _translate("IDSetupDlg", "左差右"))
        self.SelectIDTypeComboBox.setItemText(4, _translate("IDSetupDlg", "右差左"))
        self.SelectIDTypeComboBox.setItemText(5, _translate("IDSetupDlg", "对称差"))
        self.SelectIDButton.setText(_translate("IDSetupDlg", ">>"))
        self.AcceptButton.setText(_translate("IDSetupDlg", "确定"))
        self.RejectButton.setText(_translate("IDSetupDlg", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IDSetupDlg = QtWidgets.QDialog()
    ui = Ui_IDSetupDlg()
    ui.setupUi(IDSetupDlg)
    IDSetupDlg.show()
    sys.exit(app.exec_())

