# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Project\Python\QuantStudio\GUI\IDFilter.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IDFilterDlg(object):
    def setupUi(self, IDFilterDlg):
        IDFilterDlg.setObjectName(_fromUtf8("IDFilterDlg"))
        IDFilterDlg.resize(871, 318)
        IDFilterDlg.setSizeGripEnabled(True)
        self.gridLayout_3 = QtGui.QGridLayout(IDFilterDlg)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(IDFilterDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtGui.QLabel(IDFilterDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.ConditionTextEdit = QtGui.QTextEdit(IDFilterDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ConditionTextEdit.setFont(font)
        self.ConditionTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ConditionTextEdit.setObjectName(_fromUtf8("ConditionTextEdit"))
        self.gridLayout_3.addWidget(self.ConditionTextEdit, 2, 2, 1, 6)
        self.FinishButtonBox = QtGui.QDialogButtonBox(IDFilterDlg)
        self.FinishButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.FinishButtonBox.setObjectName(_fromUtf8("FinishButtonBox"))
        self.gridLayout_3.addWidget(self.FinishButtonBox, 3, 6, 1, 2)
        self.IDFilterLibTree = QtGui.QTreeWidget(IDFilterDlg)
        self.IDFilterLibTree.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.IDFilterLibTree.setObjectName(_fromUtf8("IDFilterLibTree"))
        self.gridLayout_3.addWidget(self.IDFilterLibTree, 1, 1, 3, 1)
        self.DSList = QtGui.QListWidget(IDFilterDlg)
        self.DSList.setObjectName(_fromUtf8("DSList"))
        self.gridLayout_3.addWidget(self.DSList, 1, 0, 3, 1)
        self.groupBox = QtGui.QGroupBox(IDFilterDlg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.PlusButton = QtGui.QPushButton(self.groupBox)
        self.PlusButton.setObjectName(_fromUtf8("PlusButton"))
        self.gridLayout.addWidget(self.PlusButton, 0, 0, 1, 1)
        self.DivideButton = QtGui.QPushButton(self.groupBox)
        self.DivideButton.setObjectName(_fromUtf8("DivideButton"))
        self.gridLayout.addWidget(self.DivideButton, 0, 1, 1, 1)
        self.MinusButton = QtGui.QPushButton(self.groupBox)
        self.MinusButton.setObjectName(_fromUtf8("MinusButton"))
        self.gridLayout.addWidget(self.MinusButton, 1, 0, 1, 1)
        self.PowerButton = QtGui.QPushButton(self.groupBox)
        self.PowerButton.setObjectName(_fromUtf8("PowerButton"))
        self.gridLayout.addWidget(self.PowerButton, 1, 1, 1, 1)
        self.TimeButton = QtGui.QPushButton(self.groupBox)
        self.TimeButton.setObjectName(_fromUtf8("TimeButton"))
        self.gridLayout.addWidget(self.TimeButton, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 2, 2, 1)
        self.groupBox_2 = QtGui.QGroupBox(IDFilterDlg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.GreaterButton = QtGui.QPushButton(self.groupBox_2)
        self.GreaterButton.setObjectName(_fromUtf8("GreaterButton"))
        self.gridLayout_2.addWidget(self.GreaterButton, 0, 0, 1, 1)
        self.LessButton = QtGui.QPushButton(self.groupBox_2)
        self.LessButton.setObjectName(_fromUtf8("LessButton"))
        self.gridLayout_2.addWidget(self.LessButton, 0, 1, 1, 1)
        self.GreaterEqualButton = QtGui.QPushButton(self.groupBox_2)
        self.GreaterEqualButton.setObjectName(_fromUtf8("GreaterEqualButton"))
        self.gridLayout_2.addWidget(self.GreaterEqualButton, 1, 0, 1, 1)
        self.LessEqualButton = QtGui.QPushButton(self.groupBox_2)
        self.LessEqualButton.setObjectName(_fromUtf8("LessEqualButton"))
        self.gridLayout_2.addWidget(self.LessEqualButton, 1, 1, 1, 1)
        self.EqualButton = QtGui.QPushButton(self.groupBox_2)
        self.EqualButton.setObjectName(_fromUtf8("EqualButton"))
        self.gridLayout_2.addWidget(self.EqualButton, 2, 0, 1, 1)
        self.NotEqualButton = QtGui.QPushButton(self.groupBox_2)
        self.NotEqualButton.setObjectName(_fromUtf8("NotEqualButton"))
        self.gridLayout_2.addWidget(self.NotEqualButton, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 3, 2, 2)
        self.groupBox_3 = QtGui.QGroupBox(IDFilterDlg)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.AndButton = QtGui.QPushButton(self.groupBox_3)
        self.AndButton.setObjectName(_fromUtf8("AndButton"))
        self.verticalLayout.addWidget(self.AndButton)
        self.OrButton = QtGui.QPushButton(self.groupBox_3)
        self.OrButton.setObjectName(_fromUtf8("OrButton"))
        self.verticalLayout.addWidget(self.OrButton)
        self.NotButton = QtGui.QPushButton(self.groupBox_3)
        self.NotButton.setObjectName(_fromUtf8("NotButton"))
        self.verticalLayout.addWidget(self.NotButton)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 5, 2, 2)
        self.groupBox_4 = QtGui.QGroupBox(IDFilterDlg)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.NotNullButton = QtGui.QPushButton(self.groupBox_4)
        self.NotNullButton.setObjectName(_fromUtf8("NotNullButton"))
        self.verticalLayout_2.addWidget(self.NotNullButton)
        self.NullButton = QtGui.QPushButton(self.groupBox_4)
        self.NullButton.setObjectName(_fromUtf8("NullButton"))
        self.verticalLayout_2.addWidget(self.NullButton)
        self.BracketsButton = QtGui.QPushButton(self.groupBox_4)
        self.BracketsButton.setObjectName(_fromUtf8("BracketsButton"))
        self.verticalLayout_2.addWidget(self.BracketsButton)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 7, 2, 1)
        self.TestButton = QtGui.QPushButton(IDFilterDlg)
        self.TestButton.setObjectName(_fromUtf8("TestButton"))
        self.gridLayout_3.addWidget(self.TestButton, 3, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(264, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 2, 1, 3)
        self.DSList.raise_()
        self.ConditionTextEdit.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.TestButton.raise_()
        self.FinishButtonBox.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.IDFilterLibTree.raise_()
        self.label_2.setBuddy(self.DSList)
        self.label.setBuddy(self.IDFilterLibTree)

        self.retranslateUi(IDFilterDlg)
        QtCore.QMetaObject.connectSlotsByName(IDFilterDlg)
        IDFilterDlg.setTabOrder(self.IDFilterLibTree, self.ConditionTextEdit)
        IDFilterDlg.setTabOrder(self.ConditionTextEdit, self.TestButton)
        IDFilterDlg.setTabOrder(self.TestButton, self.FinishButtonBox)
        IDFilterDlg.setTabOrder(self.FinishButtonBox, self.DSList)

    def retranslateUi(self, IDFilterDlg):
        IDFilterDlg.setWindowTitle(_translate("IDFilterDlg", "ID 过滤器", None))
        self.label_2.setText(_translate("IDFilterDlg", "<html><head/><body><p align=\"center\">因子列表</p></body></html>", None))
        self.label.setText(_translate("IDFilterDlg", "<html><head/><body><p align=\"center\">过滤器库</p></body></html>", None))
        self.IDFilterLibTree.headerItem().setText(0, _translate("IDFilterDlg", "过滤条件", None))
        self.groupBox.setTitle(_translate("IDFilterDlg", "算数运算符", None))
        self.PlusButton.setText(_translate("IDFilterDlg", "加(+)", None))
        self.DivideButton.setText(_translate("IDFilterDlg", "除(/)", None))
        self.MinusButton.setText(_translate("IDFilterDlg", "减(-)", None))
        self.PowerButton.setText(_translate("IDFilterDlg", "乘方(**)", None))
        self.TimeButton.setText(_translate("IDFilterDlg", "乘(*)", None))
        self.groupBox_2.setTitle(_translate("IDFilterDlg", "关系运算符", None))
        self.GreaterButton.setText(_translate("IDFilterDlg", ">", None))
        self.LessButton.setText(_translate("IDFilterDlg", "<", None))
        self.GreaterEqualButton.setText(_translate("IDFilterDlg", ">=", None))
        self.LessEqualButton.setText(_translate("IDFilterDlg", "<=", None))
        self.EqualButton.setText(_translate("IDFilterDlg", "==", None))
        self.NotEqualButton.setText(_translate("IDFilterDlg", "!=", None))
        self.groupBox_3.setTitle(_translate("IDFilterDlg", "逻辑运算符", None))
        self.AndButton.setText(_translate("IDFilterDlg", "且(&&)", None))
        self.OrButton.setText(_translate("IDFilterDlg", "或(|)", None))
        self.NotButton.setText(_translate("IDFilterDlg", "非(!)", None))
        self.groupBox_4.setTitle(_translate("IDFilterDlg", "其他运算符", None))
        self.NotNullButton.setText(_translate("IDFilterDlg", "非空", None))
        self.NullButton.setText(_translate("IDFilterDlg", "空", None))
        self.BracketsButton.setText(_translate("IDFilterDlg", "括号()", None))
        self.TestButton.setText(_translate("IDFilterDlg", "测试", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    IDFilterDlg = QtGui.QDialog()
    ui = Ui_IDFilterDlg()
    ui.setupUi(IDFilterDlg)
    IDFilterDlg.show()
    sys.exit(app.exec_())

