# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Project\QuantStudio\QuantStudio\Tools\QtGUI\PreviewRiskDataDlg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1161, 760)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.ColNumSpinBox = QtWidgets.QSpinBox(Dialog)
        self.ColNumSpinBox.setMaximum(9999)
        self.ColNumSpinBox.setProperty("value", 50)
        self.ColNumSpinBox.setObjectName("ColNumSpinBox")
        self.gridLayout.addWidget(self.ColNumSpinBox, 3, 3, 1, 2)
        self.IDListLabel = QtWidgets.QLabel(Dialog)
        self.IDListLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.IDListLabel.setObjectName("IDListLabel")
        self.gridLayout.addWidget(self.IDListLabel, 0, 4, 1, 1)
        self.PreviewTable = QtWidgets.QTableWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreviewTable.sizePolicy().hasHeightForWidth())
        self.PreviewTable.setSizePolicy(sizePolicy)
        self.PreviewTable.setMinimumSize(QtCore.QSize(400, 0))
        self.PreviewTable.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.PreviewTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.PreviewTable.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.PreviewTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.PreviewTable.setObjectName("PreviewTable")
        self.PreviewTable.setColumnCount(0)
        self.PreviewTable.setRowCount(0)
        self.PreviewTable.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout.addWidget(self.PreviewTable, 0, 0, 7, 1)
        self.PreviewSpecificRiskButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.PreviewSpecificRiskButton.setFont(font)
        self.PreviewSpecificRiskButton.setObjectName("PreviewSpecificRiskButton")
        self.gridLayout.addWidget(self.PreviewSpecificRiskButton, 4, 4, 1, 1)
        self.FactorList = QtWidgets.QListWidget(Dialog)
        self.FactorList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.FactorList.setObjectName("FactorList")
        self.gridLayout.addWidget(self.FactorList, 1, 1, 1, 3)
        self.PreviewRiskButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.PreviewRiskButton.setFont(font)
        self.PreviewRiskButton.setObjectName("PreviewRiskButton")
        self.gridLayout.addWidget(self.PreviewRiskButton, 5, 1, 1, 3)
        self.IDList = QtWidgets.QListWidget(Dialog)
        self.IDList.setMaximumSize(QtCore.QSize(150, 16777215))
        self.IDList.setObjectName("IDList")
        self.gridLayout.addWidget(self.IDList, 1, 4, 1, 1)
        self.Export2CSVButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Export2CSVButton.setFont(font)
        self.Export2CSVButton.setObjectName("Export2CSVButton")
        self.gridLayout.addWidget(self.Export2CSVButton, 5, 4, 1, 1)
        self.PreviewFactorRiskButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.PreviewFactorRiskButton.setFont(font)
        self.PreviewFactorRiskButton.setObjectName("PreviewFactorRiskButton")
        self.gridLayout.addWidget(self.PreviewFactorRiskButton, 4, 1, 1, 3)
        self.RowNumSpinBox = QtWidgets.QSpinBox(Dialog)
        self.RowNumSpinBox.setMaximum(9999)
        self.RowNumSpinBox.setProperty("value", 50)
        self.RowNumSpinBox.setObjectName("RowNumSpinBox")
        self.gridLayout.addWidget(self.RowNumSpinBox, 2, 3, 1, 2)
        self.ColNumLimitCheckBox = QtWidgets.QCheckBox(Dialog)
        self.ColNumLimitCheckBox.setChecked(True)
        self.ColNumLimitCheckBox.setObjectName("ColNumLimitCheckBox")
        self.gridLayout.addWidget(self.ColNumLimitCheckBox, 3, 1, 1, 2)
        self.FactorListLabel = QtWidgets.QLabel(Dialog)
        self.FactorListLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FactorListLabel.setObjectName("FactorListLabel")
        self.gridLayout.addWidget(self.FactorListLabel, 0, 1, 1, 3)
        self.RowNumLimitCheckBox = QtWidgets.QCheckBox(Dialog)
        self.RowNumLimitCheckBox.setChecked(True)
        self.RowNumLimitCheckBox.setObjectName("RowNumLimitCheckBox")
        self.gridLayout.addWidget(self.RowNumLimitCheckBox, 2, 1, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "预览风险数据"))
        self.IDListLabel.setText(_translate("Dialog", "ID"))
        self.PreviewSpecificRiskButton.setText(_translate("Dialog", "特异风险"))
        self.PreviewRiskButton.setText(_translate("Dialog", "ID 协方差阵"))
        self.Export2CSVButton.setText(_translate("Dialog", "导出 CSV"))
        self.PreviewFactorRiskButton.setText(_translate("Dialog", "因子协方差阵"))
        self.ColNumLimitCheckBox.setText(_translate("Dialog", "列数限制"))
        self.FactorListLabel.setText(_translate("Dialog", "因子"))
        self.RowNumLimitCheckBox.setText(_translate("Dialog", "行数限制"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

