# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Project\Python\QuantStudio\GUI\DateTimeSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(423, 643)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout_8 = QtGui.QGridLayout(Dialog)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.DateSetupGroupBox = QtGui.QGroupBox(Dialog)
        self.DateSetupGroupBox.setObjectName(_fromUtf8("DateSetupGroupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.DateSetupGroupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_13 = QtGui.QLabel(self.DateSetupGroupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.StartDateEdit = QtGui.QDateEdit(self.DateSetupGroupBox)
        self.StartDateEdit.setObjectName(_fromUtf8("StartDateEdit"))
        self.gridLayout_6.addWidget(self.StartDateEdit, 0, 1, 1, 1)
        self.DateListWidget = QtGui.QListWidget(self.DateSetupGroupBox)
        self.DateListWidget.setObjectName(_fromUtf8("DateListWidget"))
        self.gridLayout_6.addWidget(self.DateListWidget, 0, 2, 7, 1)
        self.label_15 = QtGui.QLabel(self.DateSetupGroupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 1, 0, 1, 1)
        self.EndDateEdit = QtGui.QDateEdit(self.DateSetupGroupBox)
        self.EndDateEdit.setObjectName(_fromUtf8("EndDateEdit"))
        self.gridLayout_6.addWidget(self.EndDateEdit, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.DateSetupGroupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_6.addWidget(self.label_16, 2, 0, 1, 1)
        self.DateTypeComboBox = QtGui.QComboBox(self.DateSetupGroupBox)
        self.DateTypeComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DateTypeComboBox.setObjectName(_fromUtf8("DateTypeComboBox"))
        self.gridLayout_6.addWidget(self.DateTypeComboBox, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.DateSetupGroupBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_6.addWidget(self.label_18, 3, 0, 1, 1)
        self.DateSouceComboBox = QtGui.QComboBox(self.DateSetupGroupBox)
        self.DateSouceComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DateSouceComboBox.setObjectName(_fromUtf8("DateSouceComboBox"))
        self.gridLayout_6.addWidget(self.DateSouceComboBox, 3, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.DateSetupGroupBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_6.addWidget(self.label_17, 4, 0, 1, 1)
        self.DateExchangeComboBox = QtGui.QComboBox(self.DateSetupGroupBox)
        self.DateExchangeComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DateExchangeComboBox.setObjectName(_fromUtf8("DateExchangeComboBox"))
        self.gridLayout_6.addWidget(self.DateExchangeComboBox, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.DateSetupGroupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 5, 0, 1, 1)
        self.DatePeriodComboBox = QtGui.QComboBox(self.DateSetupGroupBox)
        self.DatePeriodComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DatePeriodComboBox.setObjectName(_fromUtf8("DatePeriodComboBox"))
        self.gridLayout_6.addWidget(self.DatePeriodComboBox, 5, 1, 1, 1)
        self.SelectDateButton = QtGui.QPushButton(self.DateSetupGroupBox)
        self.SelectDateButton.setObjectName(_fromUtf8("SelectDateButton"))
        self.gridLayout_6.addWidget(self.SelectDateButton, 6, 1, 1, 1)
        self.gridLayout_8.addWidget(self.DateSetupGroupBox, 0, 0, 2, 2)
        self.FDBGroupBox = QtGui.QGroupBox(Dialog)
        self.FDBGroupBox.setObjectName(_fromUtf8("FDBGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.FDBGroupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_10 = QtGui.QLabel(self.FDBGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.FDBComboBox = QtGui.QComboBox(self.FDBGroupBox)
        self.FDBComboBox.setObjectName(_fromUtf8("FDBComboBox"))
        self.gridLayout_5.addWidget(self.FDBComboBox, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.FDBGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.FTComboBox = QtGui.QComboBox(self.FDBGroupBox)
        self.FTComboBox.setObjectName(_fromUtf8("FTComboBox"))
        self.gridLayout_5.addWidget(self.FTComboBox, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.FDBGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 2, 0, 1, 1)
        self.FComboBox = QtGui.QComboBox(self.FDBGroupBox)
        self.FComboBox.setObjectName(_fromUtf8("FComboBox"))
        self.gridLayout_5.addWidget(self.FComboBox, 2, 1, 1, 1)
        self.SelectFDateTimeButton = QtGui.QPushButton(self.FDBGroupBox)
        self.SelectFDateTimeButton.setObjectName(_fromUtf8("SelectFDateTimeButton"))
        self.gridLayout_5.addWidget(self.SelectFDateTimeButton, 3, 1, 1, 1)
        self.gridLayout_8.addWidget(self.FDBGroupBox, 4, 0, 1, 2)
        self.TimeSetupGroupBox = QtGui.QGroupBox(Dialog)
        self.TimeSetupGroupBox.setObjectName(_fromUtf8("TimeSetupGroupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.TimeSetupGroupBox)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_19 = QtGui.QLabel(self.TimeSetupGroupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_7.addWidget(self.label_19, 0, 0, 1, 1)
        self.StartTimeEdit = QtGui.QTimeEdit(self.TimeSetupGroupBox)
        self.StartTimeEdit.setObjectName(_fromUtf8("StartTimeEdit"))
        self.gridLayout_7.addWidget(self.StartTimeEdit, 0, 1, 1, 1)
        self.TimeListWidget = QtGui.QListWidget(self.TimeSetupGroupBox)
        self.TimeListWidget.setObjectName(_fromUtf8("TimeListWidget"))
        self.gridLayout_7.addWidget(self.TimeListWidget, 0, 2, 7, 1)
        self.label_20 = QtGui.QLabel(self.TimeSetupGroupBox)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 1, 0, 1, 1)
        self.EndTimeEdit = QtGui.QTimeEdit(self.TimeSetupGroupBox)
        self.EndTimeEdit.setObjectName(_fromUtf8("EndTimeEdit"))
        self.gridLayout_7.addWidget(self.EndTimeEdit, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.TimeSetupGroupBox)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_7.addWidget(self.label_21, 2, 0, 1, 1)
        self.TimeTypeComboBox = QtGui.QComboBox(self.TimeSetupGroupBox)
        self.TimeTypeComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TimeTypeComboBox.setObjectName(_fromUtf8("TimeTypeComboBox"))
        self.gridLayout_7.addWidget(self.TimeTypeComboBox, 2, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.TimeSetupGroupBox)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_7.addWidget(self.label_22, 3, 0, 1, 1)
        self.TimeSourceComboBox = QtGui.QComboBox(self.TimeSetupGroupBox)
        self.TimeSourceComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TimeSourceComboBox.setObjectName(_fromUtf8("TimeSourceComboBox"))
        self.gridLayout_7.addWidget(self.TimeSourceComboBox, 3, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.TimeSetupGroupBox)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_7.addWidget(self.label_23, 4, 0, 1, 1)
        self.TimeExchangeComboBox = QtGui.QComboBox(self.TimeSetupGroupBox)
        self.TimeExchangeComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TimeExchangeComboBox.setObjectName(_fromUtf8("TimeExchangeComboBox"))
        self.gridLayout_7.addWidget(self.TimeExchangeComboBox, 4, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.TimeSetupGroupBox)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_7.addWidget(self.label_24, 5, 0, 1, 1)
        self.TimePeriodComboBox = QtGui.QComboBox(self.TimeSetupGroupBox)
        self.TimePeriodComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TimePeriodComboBox.setObjectName(_fromUtf8("TimePeriodComboBox"))
        self.gridLayout_7.addWidget(self.TimePeriodComboBox, 5, 1, 1, 1)
        self.SelectTimeButton = QtGui.QPushButton(self.TimeSetupGroupBox)
        self.SelectTimeButton.setObjectName(_fromUtf8("SelectTimeButton"))
        self.gridLayout_7.addWidget(self.SelectTimeButton, 6, 1, 1, 1)
        self.gridLayout_8.addWidget(self.TimeSetupGroupBox, 3, 0, 1, 2)
        self.label_25 = QtGui.QLabel(Dialog)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_8.addWidget(self.label_25, 0, 2, 1, 1)
        self.DateTimeListWidget = QtGui.QListWidget(Dialog)
        self.DateTimeListWidget.setObjectName(_fromUtf8("DateTimeListWidget"))
        self.gridLayout_8.addWidget(self.DateTimeListWidget, 1, 2, 4, 2)
        spacerItem = QtGui.QSpacerItem(240, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 5, 0, 1, 1)
        self.RejectButton = QtGui.QPushButton(Dialog)
        self.RejectButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.RejectButton.setObjectName(_fromUtf8("RejectButton"))
        self.gridLayout_8.addWidget(self.RejectButton, 5, 3, 1, 1)
        self.AcceptButton = QtGui.QPushButton(Dialog)
        self.AcceptButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.AcceptButton.setObjectName(_fromUtf8("AcceptButton"))
        self.gridLayout_8.addWidget(self.AcceptButton, 5, 1, 1, 2)
        self.CombineButton = QtGui.QPushButton(Dialog)
        self.CombineButton.setObjectName(_fromUtf8("CombineButton"))
        self.gridLayout_8.addWidget(self.CombineButton, 2, 0, 1, 2)
        self.DateTimeNumEdit = QtGui.QLineEdit(Dialog)
        self.DateTimeNumEdit.setReadOnly(True)
        self.DateTimeNumEdit.setObjectName(_fromUtf8("DateTimeNumEdit"))
        self.gridLayout_8.addWidget(self.DateTimeNumEdit, 0, 3, 1, 1)
        self.AcceptButton.raise_()
        self.FDBGroupBox.raise_()
        self.RejectButton.raise_()
        self.DateSetupGroupBox.raise_()
        self.TimeSetupGroupBox.raise_()
        self.CombineButton.raise_()
        self.DateTimeListWidget.raise_()
        self.label_25.raise_()
        self.DateTimeNumEdit.raise_()
        self.label_13.setBuddy(self.StartDateEdit)
        self.label_15.setBuddy(self.EndDateEdit)
        self.label_16.setBuddy(self.DateTypeComboBox)
        self.label_18.setBuddy(self.DateTypeComboBox)
        self.label_17.setBuddy(self.DateTypeComboBox)
        self.label_14.setBuddy(Dialog.DateTransformComboBox)
        self.label_19.setBuddy(self.StartDateEdit)
        self.label_20.setBuddy(self.StartDateEdit)
        self.label_21.setBuddy(self.DateTypeComboBox)
        self.label_22.setBuddy(self.DateTypeComboBox)
        self.label_23.setBuddy(self.DateTypeComboBox)
        self.label_24.setBuddy(Dialog.DateTransformComboBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.DateSetupGroupBox.setTitle(_translate("Dialog", "日期设置", None))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">起始日期</p></body></html>", None))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">终止日期</p></body></html>", None))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">日期类型</p></body></html>", None))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">数据来源</p></body></html>", None))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">交易所</p></body></html>", None))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">日期周期</p></body></html>", None))
        self.SelectDateButton.setText(_translate("Dialog", ">>", None))
        self.FDBGroupBox.setTitle(_translate("Dialog", "来自因子库", None))
        self.label_10.setText(_translate("Dialog", "因子库", None))
        self.label_11.setText(_translate("Dialog", "因子表", None))
        self.label_12.setText(_translate("Dialog", "因子", None))
        self.SelectFDateTimeButton.setText(_translate("Dialog", ">>", None))
        self.TimeSetupGroupBox.setTitle(_translate("Dialog", "时间设置", None))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">起始时间</p></body></html>", None))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">终止时间</p></body></html>", None))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">时间类型</p></body></html>", None))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">数据来源</p></body></html>", None))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">交易所</p></body></html>", None))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">时间周期</p></body></html>", None))
        self.SelectTimeButton.setText(_translate("Dialog", ">>", None))
        self.label_25.setText(_translate("Dialog", "时点数", None))
        self.RejectButton.setText(_translate("Dialog", "取消", None))
        self.AcceptButton.setText(_translate("Dialog", "确定", None))
        self.CombineButton.setText(_translate("Dialog", ">>", None))
        self.DateTimeNumEdit.setText(_translate("Dialog", "0", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

